FONT = ("Courier", 30)
START_GAME_TXT = 'Start game'
END_GAME_TXT = 'End game'
QUITE_TXT = 'Quite'
LIGHT_GREY = 'light grey'
ORANGE = 'orange'
WHITE = 'white'
TIME = 60 * 3
GAME_MSG = 'Find as many words as you can'
BLACK = 'black'
TIME_TXT = 'Time'
SUBMIT_TXT = 'Submit'
WRONG_PATH_MSG = 'Invalid path !'
CHOSEN_WORD_MSG = 'You have chosen this word !'
ZERO = 0
SCORE_txt = 'Score'
GAME_TITLE = 'Boggle game'
PENCIL_CURSOR = "pencil"
WRONG_CURSOR = 'X_cursor'
EXIT_CURSOR = 'left_side'
SUBMIT_CURSOR = 'tcross'
LST_WORDS_CURSOR = 'double_arrow'
